import { StyleSheet } from 'react-native';
import { Theme } from '../../theme/colors';

export const createStyles = (theme: Theme) =>
  StyleSheet.create({
    overlay: {
      flex: 1,
      backgroundColor: 'rgba(0, 0, 0, 0.55)',
      justifyContent: 'flex-end',
    },
    container: {
      backgroundColor: theme.background,
      borderTopLeftRadius: 28,
      borderTopRightRadius: 28,
      paddingHorizontal: 24,
      paddingBottom: 32,
      maxHeight: '92%',
    },
    handleBar: {
      width: 40,
      height: 4,
      backgroundColor: theme.border,
      borderRadius: 2,
      alignSelf: 'center',
      marginTop: 12,
      marginBottom: 20,
    },
    header: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'flex-start',
      marginBottom: 20,
    },
    title: {
      fontSize: 26,
      fontWeight: '800',
      color: theme.text,
      letterSpacing: -0.3,
    },
    subtitle: {
      fontSize: 14,
      color: theme.textSecondary,
      marginTop: 2,
      fontWeight: '500',
    },
    closeButton: {
      width: 36,
      height: 36,
      borderRadius: 10,
      backgroundColor: theme.surface,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: theme.border,
      marginTop: 2,
    },
    jobInfo: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: theme.surface,
      padding: 14,
      borderRadius: 14,
      marginBottom: 24,
      gap: 12,
      borderWidth: 1,
      borderColor: theme.border,
    },
    jobInfoDot: {
      width: 8,
      height: 8,
      borderRadius: 4,
      backgroundColor: (theme as any).primary,
    },
    jobTitle: {
      fontSize: 16,
      fontWeight: '700',
      color: theme.text,
    },
    jobCompany: {
      fontSize: 13,
      color: theme.textSecondary,
      fontWeight: '500',
      marginTop: 1,
    },
    scrollContent: {
      paddingBottom: 16,
    },
    inputContainer: {
      marginBottom: 18,
    },
    label: {
      fontSize: 14,
      fontWeight: '700',
      color: theme.text,
      marginBottom: 8,
      letterSpacing: 0.1,
    },
    required: {
      color: (theme as any).danger ?? '#EF4444',
    },
    inputWrapper: {
      backgroundColor: theme.inputBackground,
      borderWidth: 1.5,
      borderColor: theme.border,
      borderRadius: 14,
      overflow: 'hidden',
    },
    inputWrapperFocused: {
      borderColor: (theme as any).primary,
    },
    inputWrapperError: {
      borderColor: (theme as any).danger ?? '#EF4444',
    },
    input: {
      padding: 14,
      fontSize: 15,
      color: theme.text,
      fontWeight: '500',
    },
    textArea: {
      minHeight: 130,
      textAlignVertical: 'top',
    },
    inputFooter: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginTop: 6,
      paddingHorizontal: 2,
    },
    errorRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
    },
    errorText: {
      color: (theme as any).danger ?? '#EF4444',
      fontSize: 12,
      fontWeight: '500',
    },
    charCount: {
      fontSize: 12,
      color: theme.textSecondary,
      fontWeight: '500',
    },
    charCountMax: {
      color: (theme as any).danger ?? '#EF4444',
    },
    submitButton: {
      backgroundColor: (theme as any).primary,
      paddingVertical: 16,
      borderRadius: 16,
      alignItems: 'center',
      flexDirection: 'row',
      justifyContent: 'center',
      gap: 8,
      marginTop: 4,
      shadowColor: (theme as any).primary,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 10,
      elevation: 5,
    },
    submitButtonLoading: {
      opacity: 0.7,
    },
    submitButtonText: {
      color: '#FFFFFF',
      fontSize: 16,
      fontWeight: '700',
      letterSpacing: 0.2,
    },

    // Success
    successOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0, 0, 0, 0.65)',
      justifyContent: 'center',
      alignItems: 'center',
      padding: 28,
    },
    successContainer: {
      backgroundColor: theme.card,
      borderRadius: 24,
      padding: 32,
      alignItems: 'center',
      width: '100%',
      maxWidth: 380,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 20 },
      shadowOpacity: 0.25,
      shadowRadius: 40,
      elevation: 20,
    },
    successIconRing: {
      width: 90,
      height: 90,
      borderRadius: 45,
      backgroundColor: (theme as any).success ?? '#10B981',
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 24,
      shadowColor: (theme as any).success ?? '#10B981',
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.4,
      shadowRadius: 16,
      elevation: 8,
    },
    successTitle: {
      fontSize: 26,
      fontWeight: '800',
      color: theme.text,
      marginBottom: 12,
      textAlign: 'center',
      letterSpacing: -0.3,
    },
    successMessage: {
      fontSize: 15,
      color: theme.textSecondary,
      textAlign: 'center',
      marginBottom: 28,
      lineHeight: 23,
    },
    successBold: {
      color: theme.text,
      fontWeight: '700',
    },
    okButton: {
      backgroundColor: (theme as any).primary,
      paddingVertical: 15,
      paddingHorizontal: 48,
      borderRadius: 14,
      width: '100%',
      alignItems: 'center',
    },
    okButtonText: {
      color: '#FFFFFF',
      fontSize: 16,
      fontWeight: '700',
      letterSpacing: 0.2,
    },
  });